add recovery and googleRecovery
questbook/zero-wallet-wagmi-connector pull request #2
Opened 2022-10-29 17:08 UTC by MohammadShahin

2022-10-29 19:24 UTC, hasankhadra requested changes

2022-10-29 19:24 UTC, hasankhadra commented on src/provider.ts
>  import { ethers } from "ethers";
You should add your scripts inside the ZeroWalletSigner not ZeroWalletProvider

2022-10-31 13:04 UTC, hasankhadra approved these changes

2022-10-31 17:02 UTC, madhavanmalolan approved these changes

2022-10-31 17:04 UTC, merged